<template>
  <div>
    <img
      id="mapImg"
      src="https://www.hamiltonhealthsciences.ca/wp-content/uploads/2018/12/mcmaster_university_medical_centre.jpg"
      loading="lazy"
    />
  </div>
</template>
